### PR TITLE
new structure & test

### PR DESCRIPTION
**Pull request by fetrarij**

### CODE REVIEW

**Comment by atais** [comment]
The tests look fine!
Good work on demo running on code from `/src/` path of this lib!

But, wow, the structure looks extremely complicated!

I loved that idea of split examples folders because that way you could simply copy such folder and have a working angular.cli or webpack application. Now when it is all embedded into one, its really hard to tell what is still a part of the lib, what is a test and what is a webpack demo or angular.cli conf file.

Was it not possible to simply make a link to `app` folder` of the other demo classes (simple, reactive, linked datetimepickers)? Or somehow make it separate and link it to both demos?

You did remove 5000 lines of code, which is great, but now I don't think any beginner could use those examples anymore. To be honest I am not sure if I could! :D
I hope you could approach it in some other way. 

Maybe let's not do everything in one go. Maybe you could 1st find a suitable way for #40 and later for #39, or the other way round... what do you think?

**Comment by atais** [comment]
Actually seems simple after some explanation, sorry I am not so up to date with Angular2+ projects.

So the last question would be:
do you think it is possible to run tests on demos served with webpack?
like if we could have:

```
npm run test:cli
npm run test:webpack
```
and cli, would do what test does now, but webpack would test if our app is working with webpack.

In that case, when I turn on CI on travis, we could test all our configs and code.
What do you think?

**Comment by fetrarij** [comment]
@atais I dont think it's needed, one test environment suffice,  and under the hood angular cli uses Webpack.

**Comment by atais** [comment]
Sorry I read your comment on weekend but did not respond :)
Well, lets go for it then.

**Comment by fetrarij** [comment]
@atais it's good for you? how about travis ci ? do you want me to do some update?

**Pull request merged**
